name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test iOS app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate iOS project structure
        run: flutter create --platforms=ios --project-name kefi_app .

      - name: Run unit tests
        run: flutter test

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
